### ISSUE TITLE
Enable GitHub workflow on pull requests

### ISSUE THREAD

**Issue by moorereason** [tierpod/dmarc-report-converter#53]
Can the GH workflow be enabled on `pull_request` instead of just `push`?  I don't think it would trigger a release since the workflow checks for tags before doing that.

I was thinking of changing the workflow to use:

```yaml
on:
  push:
  pull_request:
    paths-ignore:
      - '**.md'

```
